.MODEL SMALL       
.STACK 100H

.DATA      
   NUM1 DB 7
   NUM2 DB 4
   
.CODE          
MAIN PROC  
    MOV AX, @DATA
    MOV DS, AX
    
    MOV AL, NUM1               ;AL =03H HERE ASSINGED
    SUB AL, NUM2               ;SUB NUM2 INTO NUM1 THAT IS ALREADY IN AL, 3 + 4 =7
    
    ; CURRENTLY CPU HAS NO 7 NOT A CHARACTER 7 SO THIS MEANS 7 AS A NUMERIC VALUE 00000111 BUT IF 
    ;WE WANT TO DISPLAY 7 DOS EXPECTS THE ASCII CHARACTER
    ; ASCII: '7' = 37H, WHILE 7 = 07H, ADDING 0 CONVERTS A SINGLE DIGIT RESULT INTO ITS CORRESPONDIG PRINTABLE ASCII CHARACTER
    
    ADD AL, '0' ; PRINTABLE ASCII CHARACTER, (AL = 07H) + ('0' = 30H) = 37H AND 37H = ASCII '7' 
    ;BEFORE: AL = 07H, AFTER: 37H THATS WHY ADD AL, '0'
    
    ;MOVING CHARACTER INTO DL
    MOV DL, AL ; DL = 37H-->'7'
    MOV AH, 02H ; DISPLAY CHARACTER  
    INT 21H
    
    ;TERMINATE
    MOV AH, 4CH
    INT 21H      
    
MAIN ENDP
END MAIN
    
    
    